# Generated by Django 4.1.7 on 2023-03-17 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milldata', '0002_company_contract_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='feed_hold_time',
            new_name='galla_clear_time',
        ),
    ]
