# Generated by Django 4.1.7 on 2023-03-17 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milldata', '0003_rename_feed_hold_time_device_galla_clear_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milldata',
            old_name='feed_hold_time',
            new_name='galla_clear_time',
        ),
    ]
