# Generated by Django 4.1.7 on 2023-03-17 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('milldata', '0004_rename_feed_hold_time_milldata_galla_clear_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milldata',
            name='data',
        ),
        migrations.RemoveField(
            model_name='milldata',
            name='galla_clear_time',
        ),
        migrations.RemoveField(
            model_name='milldata',
            name='initial_hold',
        ),
        migrations.RemoveField(
            model_name='milldata',
            name='overload_hold',
        ),
        migrations.AddField(
            model_name='milldata',
            name='feed_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='milldata',
            name='katta_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='milldata',
            name='katta_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milldata',
            name='overload_status',
            field=models.BooleanField(default=False),
        ),
    ]
