# Generated by Django 4.1.7 on 2023-03-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milldata', '0006_alter_milldata_katta_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milldata',
            name='katta_time',
            field=models.DateTimeField(),
        ),
    ]
