# Generated by Django 4.1.7 on 2023-04-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milldata', '0007_alter_milldata_katta_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='galla_vibrator_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='device',
            name='hopper_vibrator_status',
            field=models.BooleanField(default=True),
        ),
    ]
