# Generated by Django 4.1.7 on 2023-04-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milldata', '0009_milldata_galla_clear_time_milldata_initial_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='milldata',
            name='overload_hold',
            field=models.IntegerField(default=900),
            preserve_default=False,
        ),
    ]
