# Generated by Django 4.2 on 2023-04-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milldata', '0010_milldata_overload_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='wait_bags',
            field=models.IntegerField(blank=True, default=3),
        ),
    ]
